"""add mycourse

Revision ID: 3176e6dde81e
Revises: c43ff2742aaa
Create Date: 2026-02-25 12:56:53.328087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3176e6dde81e'
down_revision = 'c43ff2742aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_course')
    # ### end Alembic commands ###
